### ISSUE TITLE
Private static members

### ISSUE THREAD

**Issue by johnpdpkarp** [USGS-Astrogeology/CSM-CameraModel#1]
In MdisPlugin.h

I don't think this is necessary, since they are already forward declared in Plugin.h

namespace csm {
  class Isd;
  class Model;
  class Warning;
}

Since the following are all private in MdisPlugin.h would suggest not declaring them in the header at all....

 static const MdisPlugin m_registeredPlugin;
 static const std::string m_pluginName;
 static const std::string m_manufacturerName;
 static const std::string m_releaseDate;
 static const csm::Version m_csmVersion;
 static const int m_numModels;

Instead, just declare them in the cpp file.

**Comment by jlaura** [comment]
As a comment - I cleaned out the namespace lines.
