### ISSUE TITLE
Move to accepting one of the standard ISD formats in the plugin

### ISSUE THREAD

**Issue by jessemapel** [USGS-Astrogeology/CSM-CameraModel#109]
We need to move the JSON ISD parsing into the Plugin. The SETs will have no knowledge of how to parse the JSON or even that it exists. We need to modify the Plugin so that it takes the default ISD class that has been constructed with an image filename.

**Comment by kberryUSGS** [comment]
I'm updating 'UsgsAstroFramePlugin::contructModelFromISD` to take the default ISD class (instead of something already populated with parsed values) and do the parsing itself (I'm probably going to start this with a copy from the SET Stuart and I worked on in c++ that did this parsing.)

**Comment by jessemapel** [comment]
:+1:

**Comment by kberryUSGS** [comment]
@jessemapel Right now, all that `contructModelFromISD` takes is a `csm::Isd` and a `std::string modelName`. Where would the actual image filename come into this process, if the goal is to find a sidecar .json file next to the image itself?
