### ISSUE TITLE
Should the Anaconda build calls in our CI be post merge?

### ISSUE THREAD

**Issue by jessemapel** [USGS-Astrogeology/CSM-CameraModel#122]
Right now, we push to Anaconda as soon as a PR is submitted and CI testing passes. Should we push the build to Anaconda after the PR is merged? Can we even do this through Travis?

**Comment by jlaura** [comment]
Right now the build and push autofails when the PR is submitted as the `$CONDA_UPLOAD_TOKEN` is not defined on PRs. We could include the following to make this more explicit:

```bash
if [ "${TRAVIS_PULL_REQUEST}" = "false" ] ;then
      conda build --token $CONDA_UPLOAD_TOKEN recipe -q;
fi
```

Alternatively, if we also want to test that the conda build is going to work, we could push a block like the following into the script section. One issue we have now is that all of our testing could pass on a merged PR and then the conda build could fail silently.

Inside of `script:`
```bash
if [ "${TRAVIS_PULL_REQUEST}" = "false" ] ;then
      conda build --token $CONDA_UPLOAD_TOKEN recipe -q;
else
      conda build recipe -1;
fi
```

**Comment by jessemapel** [comment]
It seems like this has been answered and resolved?
