### ISSUE TITLE
Finished ORex MapCam Implementation

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/CSM-CameraModel#13]
- [x] Determine if the MapCam can utilize the generic framer
- [ ] Implement if necessary
- [ ] Generate tests

**Comment by jessemapel** [comment]
Based on the ISIS3 camera model, there is nothing unusual about the mapcam. The generic framing camera model should work if we can generate an ISD for it.

**Comment by jessemapel** [comment]
Nevermind, current framer implementation uses polynomial distortion. ORex MapCam and PolyCam define their distortion radially. We also have to account for differences between camera boresight and distortion center. See the end of this IK
https://naif.jpl.nasa.gov/pub/naif/ORX/kernels/ik/orx_ocams_v06.ti

**Comment by jessemapel** [comment]
It's also going to require a new system for computing distorted coordinates from undistorted coordinates. Computing the jacobian of radial distortion is clunky and odd. It makes more sense to work purely along the radii. See https://github.com/USGS-Astrogeology/ISIS3/blob/dev/isis/src/osirisrex/objs/OsirisRexOcamsCamera/OsirisRexOcamsCamera.cpp

**Comment by jlaura** [comment]
This will be covered by #24
