### ISSUE TITLE
GXP returns a error for all images it loads

### ISSUE THREAD

**Issue by thareUSGS** [USGS-Astrogeology/CSM-CameraModel#133]
I think the Framer/Scanner needs to not return an error. Perhaps not even a warning. But the application does need to know it didn't work. I thinking looking at the original code might list what we need to return.

here is the error
 Line 1336 : DEBUG : ERROR: Could not read metadata file associated with image: C:\Program Files\BAE SYSTEMS\SOCET GXP 4.3.0\Config\VCT\Maps\TrueMarble\TrueMarble-2km-21600x10800.json-UsgsAstroFramePlugin::loadImageSupportData

The good news is that GXP loaded the DLL!

**Comment by jessemapel** [comment]
This is likely a problem with UsgsAstroFramePlugin::canISDBeConvertedToModelState

It needs to catch any errors from UsgsAstroFramePlugin::loadImageSupportData and simply return false
