### ISSUE TITLE
Finished ORex PolyCam Implementation

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/CSM-CameraModel#14]
- [ ] Determine if the MapCam can utilize the generic framer
- [ ] Implement if necessary
- [ ] Generate tests

**Comment by jessemapel** [comment]
A lot of the work being done for #13 will solve this issue. PolyCam has the additional issue of variable focal length settings. A full up implementation will need more work and probably some special correspondences with the mission team.

**Comment by jessemapel** [comment]
@kberryUSGS may have more information about how the variable focal settings impacts the camera model. There is some amount of additional calculations that it imposes.

**Comment by jlaura** [comment]
This will be covered by #24 and the ISD stuff.
