### ISSUE TITLE
Make the Plugins Singletons

### ISSUE THREAD

**Issue by Kelvinrr** [USGS-Astrogeology/CSM-CameraModel#144]
From the CSM specification: 

>The CSMPlugin base class owns a list of all derived sensor model plugins that are
currently installed and available for image processing. In actuality, this list is a list of
pointers to the factory classes for the respective derived plugins. Client software can
access this list of pointers through the CSMPlugin::getList()function.
Registration is the process whereby derived plugins get added to the base class list.
The CSMPlugin base class provides a mechanism allowing derived plugins to “selfregister”
with the base class, thereby adding themselves to the base class list. This
mechanism is described below.
The CSMPlugin base class (see header files CSMPlugin.h) has the a constructor
CSMPlugin::CSMPlugin() that can only be called by objects that derive from the base
class. This constructor adds the calling object’s pointer to a list of known derived type
plugins. An example for CSMPlugin construction, as follows: 
>
>csmPlugin::csmPlugin() 
{
 if (!theList)
 {
 theList = new csmPluginList;
 }
 if (theList)
 {
 theList->push_back(this);
 }
}
>
>Derived plugins must contain a static instance of themselves (i.e., a static instance of
the derived type plugin). The effect of having the static instance is that when the runtime
library gets loaded by the application, the static instance gets initialized resulting in the
base class constructor adding the derived plugin to its list.

This seems to imply that the plugins should ideally be singletons. Probably worth making that change in our own implementations.

**Comment by jessemapel** [comment]
This is already done, see https://github.com/USGS-Astrogeology/CSM-CameraModel/blob/dev/include/usgscsm/UsgsAstroPlugin.h#L53

**Comment by Kelvinrr** [comment]
Oof, thanks for pointing that out, didn't notice.
