### ISSUE TITLE
Linkers 

### ISSUE THREAD

**Issue by thareUSGS** [USGS-Astrogeology/CSM-CameraModel#20]
Help getting build to work better.

**Comment by jessemapel** [comment]
The problem appears to be caused by conda build only using gcc 4. @jlaura is currently working on compiling things without conda build and then pushing them up the anaconda cloud.

This is less a problem with this library as it is with the lbcsm and cycsm libraries.

**Comment by jlaura** [comment]
This has been fixed to use gxx7.2 in the latest uploads to anaconda.org.  This includes libcsm, cycsm, and usgscam. If rebuilding one of these, gxx7.2 needs to be used.
