### ISSUE TITLE
Testing i2g and g2i script running down center of image -- output CSV

### ISSUE THREAD

**Issue by thareUSGS** [USGS-Astrogeology/CSM-CameraModel#21]
This could be a Python script or Jupiter notebook simply running down the center of the image testing about every ~100 rows. The output CSV should emulate a Socet SET program we had to do the same called "SsIsisValidationG2I_imgLength". I think it could also run down both sides (~10% in from the side).

original code: /work/projects/socetset/DPW/SSv56/devkit/SENSOR_MODELS/SsIsisValidationG2I_imgLength/SsIsisValidationG2I_imgLength.cpp

more (from original .cpp header): 
// This program gathers the Socet Set information needed to validate ISIS->SOCET SET
// translation code and/or newly developed Sensor Models by comparing the ground-to-image results
// in ISIS and SOCET SET.   The input images used for these tests must have been spiceinit'ed
// to the ellipsoid in ISIS.  In SOCET SET, we must gather ground-to-image calculations at
// Z/ELEV =0.0 because ISIS assumes Z/ELEV =0.0 when spiceinit'd to the ellipsoid.
//
// This program will also compare the SOCET SET Sensor's model forward and backward
// calculations (ImgToGrnd then GrndToImg) and report the difference in the starting
// and ending line/sample calculations.
//
// This program will gather GrndToImg results at he CENTER of the image, and 10% in from
// the image corners for UL, UR, LL, LR results.  To get the input ground coordinate, it starts with
// ImgToGrnd calculations at the CENTER, UL, UR, LL, LR image coordinates.  The resulting ground
// coordinate is then used as input to GrndToImg.  The input ground coordinate to GrndToImg, and the
// output image coordinate from GrndToImg are written to an output csv file, which will  be an input file
// to ISIS script SsIsisValidationGrd2Img.pl.  This ISIS script will gather the ISIS results, and
// difference the SOCET SET and ISIS line/sample results.
//
// Furthermore, this program will convert and report the various coordinate systems and formats used
// in SOCET SET and ISIS.  The header line in the output CSV will contain an "ss" prefix on the SOCET
// SET values, and an "isis" prefix for ISIS values.  Each column in the CSV file is as follows:
//
//    _Update for CSM_
//
//      **ISD_Name**:
//           The ISD used for processing the image
//
//       **imgRegion** (optional):
//           CENTER, UL, LL, UR, LR regions tested
//
//       **csmImgCentLine_I2G, csmImgCentSamp_I2G**:
//           SOCET SET image-centered coordinate input to image2ground
//
//       **csmLatOG, csmLon180, csmElev**:
//           Ground coordinate lat/lon/Elev result from image2ground
//
//       **ssImgCentLine_G2I, ssImgCentSamp_G2I**:
//           image-centered coordinate result from ground2image
//
//       **csmSensorDeltaLine, csmSensorDeltaSamp**:
//           Difference in line/sample coordinates btw image2ground and ground2image
//
//       **csm2isisLine_G2I, csm2isisSamp_G2I**:
//           ground2image image coord converted to ISIS line/sample coord
//
//       **isisLatOC,isislon360**:
//           CSM lat/lon coordinate in ISIS ocentric-lat/E360-lon system
///////////////////////////////////////////////////////////////////////////////

Some of the helper functions just to show the pixel and lat/lon conversion to ISIS coords. Last function just for ographic to ocentric lats.

```
image_point_struct
isis2ssLS(image_point_struct isisPt, int nlines, int nsamples)
// Convert ISIS line/sample coordinates to SOCET SET image-centered coordinates
{
   image_point_struct ssPt;
   ssPt.line = isisPt.line - 0.5 * nlines -1.0;
   ssPt.sample = isisPt.sample -0.5 * nsamples - 1.0;
    return(ssPt);
} // End isis2ssLS

image_point_struct
ss2isisLS(image_point_struct ssPT, int nlines, int nsamples)
// Convert SOCET SET image-centered coordinates to ISIS line/sample coordinates
{
   image_point_struct isisPt;
   isisPt.line = ssPT.line + 0.5 * nlines + 1.0;
   isisPt.sample = ssPT.sample + 0.5 * nsamples + 1.0;
    return(isisPt);
} // End ss2isisLS

void
ss2isisGRD(ground_point_struct ss_gp, double eccSqr, double *ocLat, double *lon360, double *Elev)
// Convert SOCET SET lat/lon coordinates to ISIS lat/lon coordinates
{
  double r2d=57.295779513082320876798154814105;
  if (eccSqr == 0.0)
    *ocLat = ss_gp.y * r2d;
  else {
    *ocLat = atan(tan(ss_gp.y) * (1-eccSqr)) * r2d;
  }
  if (ss_gp.x > 0.0)
    *lon360 = ss_gp.x * r2d;
  else {
    *lon360 = ss_gp.x  * r2d + 360.0;
  }
  *Elev = ss_gp.z;
  return;
} // End ss2isisGRD
```

**Comment by jlaura** [comment]
This is external to this repo.

**Comment by thareUSGS** [comment]
Just playing around for a little: https://gist.github.com/thareUSGS/9efcb777725dc0a58a4e8b29a299f11f

Will push ticket under SET
