### ISSUE TITLE
Remove unused enum in UsgsAstroISD.h ?

### ISSUE THREAD

**Issue by kberryUSGS** [USGS-Astrogeology/CSM-CameraModel#27]
The `IsdKeywords enum` doesn't seem to be actually used anywhere (everything compiles and there are no test failures when this is commented out.) It contains an (unnecessary?) additional list of the ISD keywords that we'd need to keep updated.

**Comment by twilson271828** [comment]
The CameraModel project compiles just fine if the whole thing is commented out.  I don't know what it's doing there.

**Comment by jessemapel** [comment]
I think it was suppose to be used the same was as the state keywords enum is used in the line scan state data. We should took a good hard look at all of that anyways, so I see no problem with removing it for right now.

**Comment by jessemapel** [comment]
As far as I know, the entire UsgsAstroISD class is unused. So, we can just delete the whole thing.

**Comment by kberryUSGS** [comment]
This appears to already be taken out, so I'm closing this issue.
