### ISSUE TITLE
CTX Sensor groundToImage

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/CSM-CameraModel#36]
The CTX tests were disabled during the last sprint.  It looks like the groundToImage call is not working with CTX data.  To replicate add the following to the `test_genericls.py` file:

```python
class TestCTX:

    @pytest.mark.parametrize('image, ground',[
                              ((2500, 9216, 0), (-73589.5516508502, 562548.342040933, 2372508.44060771)),
                              ((100,100,0), (712929.1383706382, 3158202.49568922, 1019437.3888700278))])
    def test_image_to_ground(self, ctx_model, image, ground):
        gx, gy, gz = ground
        x, y, z = ctx_model.imageToGround(*image)

        #TODO: Get this test up and running.
        #print(x, y, z)
        #assert False
        assert x == pytest.approx(gx, rel=1)
        assert y == pytest.approx(gy, rel=1)
        assert z == pytest.approx(gz, rel=1)


    @pytest.mark.parametrize('image, ground',[
                              ((2500, 9216, 0), (-73589.5516508502, 562548.342040933, 2372508.44060771)),
                              ((100,100,0), (712929.1383706382, 3158202.49568922, 1019437.3888700278))])
    def test_ground_to_image(self, ctx_model, image, ground):
        y, x = ctx_model.groundToImage(*ground)
        ix, iy, _ = image
        assert x == pytest.approx(ix)
        assert y == pytest.approx(iy)
```

`imageToGround` has NOT been validated yet using an existing sensor model either. `groundToImage` fails with an error being raised for either the ground point not being in the image or the convergence failing.

**Comment by jessemapel** [comment]
Looking at past versions, the CTX tests were never actually turned on.

**Comment by jlaura** [comment]
:+1: correct I just started testing these. The tests above are bad too - they are just eating our own dog food to try and round trip from sensor to surface and back again. So, the error could be on the imageToGround side just as easily.

**Comment by jessemapel** [comment]
Does anyone know where the ISD that is being used for this test comes from? We'll need that in order to generate numbers in ISIS to validate.

**Comment by jlaura** [comment]
https://github.com/USGS-Astrogeology/CSM-CameraModel/blob/master/tests/J03_046060_1986_XN_18N282W_8bit_keywords.lis

**Comment by jlaura** [comment]
Ahh, nope. Nada on this image.  I will pull an image tomorrow AM where we
know exactly how it was generated.

**Comment by jlaura** [comment]
In `/home/jlaura/ctx_test` I have put a spiceinited cub and a CSM generated ISD file (JSON).
