### ISSUE TITLE
categorize ISIS3 calls really needed by camera, spice, other

### ISSUE THREAD

**Issue by thareUSGS** [USGS-Astrogeology/CSM-CameraModel#37]
**ISIS3 Camera functions in no particular order**

- RA - Sensor::computeRaDec()
- DEC - Sensor::computeRaDec()
- Radii - Target::radii
- Planetocentric Lat (Universal Lat) - Target->Shape->surfaceIntersection->SurfacePoint::GetLatitude
- Planetographic Lat - Get radii, get universal lat, TProjection::ToPlanetographic
- Positive East 360 Lon (Universal Lon) - Target->Shape->surfaceIntersection->SurfacePoint::GetLongitude
- Positive East 180 Lon - Get universal lon, TProjection::To180Domain
- Positive West 360 Lon - Get universal lon, TProjection::ToPositiveWest
- Positive West 180 Lon - Get positive west 360, TProjection::To180Domain
- Body Fixed X,Y,Z - Target->Shape->SurfactPoint::GetX/Y/Z
- Local Radius - Target->Shape->SurfactPoint::GetLocalRadius
- Pixel Resolution - PixelResolution->GetLine/SampleResolution()->Camera::DetectorResolution
- Line Resolution - Camera::DetectorResolution * DetectorMap::LineScaleFactor
- Sample Resolution - Camera::DetectorResolution * DetectorMap::SampleScaleFactor
- Detector Resolution - Camera::DetectorResolution
- Spacecraft Position - SpiceRotation::ReferenceVector
- Spacecraft Azimuth - Camera::SpacecraftAzimuth(Spice::subSpacecraftPoint, Camera::ComputeAzimuth)
- Slant Distance - Sensor::SlantDistance
- Target Center Distance - Spice::targetCenterDistance
- Subspacecraft Lat - Spice::subSpacecraftPoint
- Subspacecraft Lon - Spice::subSpacecraftPoint
- Spacecraft Altitude - Sensor::SpacecraftAlititude
- OFFNADIR Angle - Camera::OffNadirAngle
- Subspacecraft Ground Azimuth - Camera:GroundAzimuth
- Sun Position  - Spice::sunPosition
- Subsolar Azimuth - Camera::SolarAzimuth(Spice::subSolarPoint, Camera::ComputeAzimuth)
- Solar Distance - Sensor::SolarDistance
- Subsolar Lat - Spice::subSolarPoint
- Subsolar Lon - Spice::subSolarPoint
- Subsolar Ground Azimuth - Camera::GroundAzimuth
- Phase - ShapeModel::phaseAngle
- Emission - ShapeModel::emissionAngle
- Incidence - ShapeModel::incidenceAngle
- Local Phase - Camera::LocalPhotometricAngles
- Local emission - Camera::LocalPhotometricAngles
- Local Incidence - Camera::LocalPhotometricAngles
- North Azimuth - Get universal lat, Camera::ComputeAzimuth
- Distorted Focal Plane X, Y, Z - Camera::FocalPlaneMap->FocalPlaneMap::FocalPlaneX/Y
- Undistorted Focal Plane X, Y, Z - Camera::DistortionMap->UndistortedFocalPlaneX/Y/Z
- Ephemeris Time - Spice::time
- UTC - Spice::time
- Local Solar Time - Sensor::LocalSensorTime
- Solar Longitude - Spice::computeSolarLongitude

**Comment by jessemapel** [comment]
This is more appropriate for a SET or the SensorUtils library. I'm going to close it on here.
