### ISSUE TITLE
MdisPlugin methods

### ISSUE THREAD

**Issue by johnpdpkarp** [USGS-Astrogeology/CSM-CameraModel#4]
The model family name being returned by MdisPlugin is incorrect.

Current code 

std::string MdisPlugin::getModelFamily(size_t modelIndex) const {
  return "Raster";
}

This should actually be "GeometricRaster" if the model being returned is a RasterGM... See RasterGM.h and GeometricModel.h for details.

I think there may be a misunderstanding of "state"   Construction of a model from a "state" is not supposed to be optional.  It looks like the support data you construct from could easily be written out and read back in... this would be the "state"... simply a way of persisting the information necessary to instantiate a model...   The method canModelBeConstructedFromState() is not implying doing so is optional, but rather is asking if a model can be constructed from the "specific" state being passed in.

**Comment by jlaura** [comment]
Fixed in 54ae463d.

**Comment by jlaura** [comment]
I implemented and exposed in the Python wrapper for testing the following.

In the plugin:

- canModelBeConstructedFromState
- canModelBeConstructedFromISD
- constructModelFromState
- getModelNameFromModelState
- canISDBeConvertedToModelState
- convertISDToModelState

In the camera:

- Fixed issue with getting modifiable parameters
- getModelState
