### ISSUE TITLE
Set up ctest

### ISSUE THREAD

**Issue by jessemapel** [USGS-Astrogeology/CSM-CameraModel#47]
We've tried gtest in the past and it didn't play nice with cmake. ctest should work better with cmake.

**Comment by jlaura** [comment]
From what I am seeing GTest is the framework to write C++ tests and CTest is the test collector and executor.  It looks like CMake 3.10+ should play nicely with GTest for writing the tests and CTest for executing them. It looks like [`gtest_discover_tests`](https://blog.kitware.com/dynamic-google-test-discovery-in-cmake-3-10/) is a way to have rich verbosity during test execution.

**Comment by jessemapel** [comment]
Closed by #56
