### ISSUE TITLE
What do we deliver?

### ISSUE THREAD

**Issue by jessemapel** [USGS-Astrogeology/CSM-CameraModel#48]
Should we make our headers (UsgsAstroLsSensorModel.h, etc.) available?

This is basically a plugin. How do we create that with cmake?

**Comment by jessemapel** [comment]
See page 18 of the CSM spec (http://gwg.nga.mil/documents/csmwg/documents/CSM_TRD_Appendix_C_API_Version_3.0__15_November_2010.pdf)

**Comment by jlaura** [comment]
I think we have our answer on this?

> CSM plugins are always provided in a form that can be distributed to potential users and installed in applications that require sensor models. Each plugin takes the form of a runtime linkable library that can be incorporated and by applications at runtime.

We can reopen if needed.
