### ISSUE TITLE
Can we have a single plugin for the library?

### ISSUE THREAD

**Issue by jessemapel** [USGS-Astrogeology/CSM-CameraModel#51]
We have separate framing camera and line scan camera plugins right now. Can we combine those into a single plugin?

**Comment by jlaura** [comment]
We should be able to go to a single plugin. @thareUSGS and I were talking about this today. We have spent some time trying to generalize the ISD to the point that generic XYZ are usable, but given the existing plugin architecture, why not just utilize as simple an ISD as possible, the some good old command-c/command-v. All of the obvious maintenance and duplication issues exist, but in terms of short term, get things implemented, this seems a viable approach.

**Comment by jessemapel** [comment]
I think the answer on this is yes. See #108 for the "do it"
