### ISSUE TITLE
Fix windows builds

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/CSM-CameraModel#55]
It looks like the windows builds are going to need some additional flags due to how MS wants DLLs handled. 

Example error: `'UsgsAstroFramePlugin::m_registeredPlugin': definition of dllimport static data member not allowed`

[StackOverflow discussion](https://stackoverflow.com/questions/3491990/c-definition-of-dllimport-static-data-member) of this issue.

**Comment by thareUSGS** [comment]
vs2017 is the target for GXP - so yes.

**Comment by jlaura** [comment]
@AstroKEW78 See https://github.com/USGS-Astrogeology/CSM-CameraModel/blob/master/.appveyor.yml

The issue is going to be win. install guards, setting up CMake install to be win compliant, etc.

**Comment by jlaura** [comment]
https://ci.appveyor.com/project/jlaura/csm-cameramodel/builds/19639956 

The fix is in dev and will port into master once we get dev merged in there.

**Comment by jessemapel** [comment]
https://media.giphy.com/media/3oKIPf3C7HqqYBVcCk/giphy.gif
