### ISSUE TITLE
CI testing should be able to support including objects/namespaces in the SensorUtils lib

### ISSUE THREAD

**Issue by twilson271828** [USGS-Astrogeology/CSM-CameraModel#68]
At some point in the future.  It doesn't have to happen immediately.

**Comment by makaylas** [comment]
This needs to be moved to the SensorUtils issue tracker

**Comment by jessemapel** [comment]
Why do we want this here? This creates a weird circular dependency. We should be testing the direct output of the CSM camera model. Then, an integration test can handle integration with SensorUtils.
