### ISSUE TITLE
update to socetlinescankeywords

### ISSUE THREAD

**Issue by thareUSGS** [USGS-Astrogeology/CSM-CameraModel#9]
During the write of the ISD (keywords.lis) file we need to add two more keywords. These make sense to be towards the top of the file - perhaps just under "SENSOR_TYPE" and "SENDOR_MODE". The two keywords are:

SEMI_MAJOR_AXIS 
ECCENTRICITY

Perhaps some pseudo code. I have no idea if this is the correct method to grab equatorial and polar radii from a level 0 or 1 cube.

```
    if (mapping.hasKeyword("EquatorialRadius") && mapping.hasKeyword("PolarRadius")) {
      m_equatorialRadius = new Distance(toDouble(mapping["EquatorialRadius"][0]),
                                        Distance::Meters);
      m_polarRadius = new Distance(toDouble(mapping["PolarRadius"][0]),
                                   Distance::Meters);
    }
    else {
      try {
        PvlGroup radiiGrp = Target::radiiGroup(mapping["TargetName"][0]);
        m_equatorialRadius = new Distance(toDouble(radiiGrp["EquatorialRadius"][0]),
                                          Distance::Meters);
        m_polarRadius = new Distance(toDouble(radiiGrp["PolarRadius"][0]),
                                     Distance::Meters);
      }
      catch (IException &e) {
        QString msg = "Unable to grab radii from cube.";
        throw IException(e, IException::Unknown, msg, _FILEINFO_);
      }
    }

     m_eccentricity = 1.0 -
                      (m_polarRadius * m_polarRadius) /
                      (m_equatorialRadius * m_equatorialRadius);
     m_eccentricity = sqrt(m_eccentricity);
```

so:
SEMI_MAJOR_AXIS m_equatorialRadius
ECCENTRICITY m_eccentricity

e.g. Mars 
RECTIFICATION_TERMS
        3.00000000000000e+04 0.00000000000000e+00 1.00000000000000e+00
        1.00000000000000e+04 1.00000000000000e+00 0.00000000000000e+00
GROUND_ZERO 4.27444857125941e-01 -3.26805190989393e-01 0.00000000000000e+00
LOAD_PT 4.27444857125941e-01 -3.26805190989393e-01 0.00000000000000e+00
COORD_SYSTEM 1
IMAGE_MOTION 0
SENSOR_TYPE USGSAstroLineScanner
SENSOR_MODE UNKNOWN
SEMI_MAJOR_AXIS 3.39619000000000e+006
ECCENTRICITY 1.08339143554195e-001
...

**Comment by thareUSGS** [comment]
Ken E. has implemented a couple commented blocks (ISIS ticket ?). Need to turn these on.

**Comment by jessemapel** [comment]
Changes are here https://github.com/jessemapel/ISIS3/tree/socetkeys

**Comment by thareUSGS** [comment]
initial testing successful. closed
