### ISSUE TITLE
focal length in meters?

### ISSUE THREAD

**Issue by AstroKEW78** [USGS-Astrogeology/CSM-CameraModel#96]
We should consider changing the units of focal length to meters (and maybe the other length units as well).

**Comment by thareUSGS** [comment]
While using one unit would be nice, focal length seems to be always in mm. I would vote to keep that. I just mainly wanted to update radius to be meters (from kilometers).

**Comment by jlaura** [comment]
I thought that we discussed this at a standup. `mm` it is.
